# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gcig_ca125 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gcig_ca125"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Paul D Mitchell"]
  s.date = "2015-03-09"
  s.description = " A Ruby gem of calculating the response of Ovarian cancer patient\naccording to levels of CA 125 as defined by the GCIG"
  s.email = "paul.d.mitchell@ed.ac.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "gcig_ca125.gemspec",
    "lib/gcig_ca125.rb",
    "lib/gcig_ca125/calculator.rb",
    "lib/gcig_ca125/result.rb",
    "lib/gcig_ca125/version.rb",
    "spec/data/gcig_test_data.csv",
    "spec/gcig_ca125_spec.rb",
    "spec/lib/gcig_ca125/calculator_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/test_data_reader.rb"
  ]
  s.homepage = "http://github.com/yatsura/gcig_ca125"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.2"
  s.summary = "Response and progression of ovarian cancer according to serum CA 125 levels"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<codeclimate-test-reporter>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<codeclimate-test-reporter>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<bundler>, ["~> 1.7"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<codeclimate-test-reporter>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<bundler>, ["~> 1.7"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

